services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: securebank
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 54322:5432
volumes:
  pgdata: